### ISSUE TITLE
System.ArgumentNullException when loading big sprites.

### ISSUE THREAD

**Issue by Borkason** [SiliconStudio/paradox#174]
I stumbled upon a bug when loading an Entity containing a SpriteGroup with an image that has a size of 76 x 11590 pixels. (Don't laugh :wink:)

http://forums.paradox3d.net/t/system-argumentnullexception-loading-an-asset/131

**Comment by xen2** [comment]
You can't load texture larger than 4096 with `GraphicsProfile.Level_9_1`.
Please switch to `GraphicsProfile.Level_11_0` in your game constructor.

Still, what we should fix on our side is:
- asset build error (since we know which profile we compile against)
- throw a runtime exception when loaded

**Comment by xen2** [comment]
Small update:
- Asset build error will now be displayed
- At runtime, there is already something in the log/debugger when a texture fails to load:

```
[GPUTexture]: Error: Unable to load Texture test_large__IMAGE_TEXTURE__0. See Debug for more information. SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at SharpDX.Direct3D11.Texture2D..ctor(Device device, Texture2DDescription description, DataBox[] data)
   at SiliconStudio.Paradox.Graphics.Texture.InitializeFromImpl(DataBox[] dataBoxes) in c:\DEV\paradox\sources\engine\SiliconStudio.Paradox.Graphics\Direct3D\Texture.Direct3D.cs:line 110
   at SiliconStudio.Paradox.Graphics.Texture.InitializeFrom(Texture parentTexture, TextureDescription description, TextureViewDescription viewDescription, DataBox[] textureDatas) in c:\DEV\paradox\sources\engine\SiliconStudio.Paradox.Graphics\Texture.cs:line 457
   at SiliconStudio.Paradox.Graphics.Texture.InitializeFrom(TextureDescription description, TextureViewDescription viewDescription, DataBox[] textureDatas) in c:\DEV\paradox\sources\engine\SiliconStudio.Paradox.Graphics\Texture.cs:line 415
   at SiliconStudio.Paradox.Graphics.Texture.New(GraphicsDevice graphicsDevice, TextureDescription description, TextureViewDescription viewDescription, DataBox[] boxes) in c:\DEV\paradox\sources\engine\SiliconStudio.Paradox.Graphics\Texture.cs:line 1064
   at SiliconStudio.Paradox.Graphics.Texture.New(GraphicsDevice graphicsDevice, TextureDescription description, DataBox[] boxes) in c:\DEV\paradox\sources\engine\SiliconStudio.Paradox.Graphics\Texture.cs:line 1045
   at SiliconStudio.Paradox.Graphics.Texture.New(GraphicsDevice device, Image image, TextureFlags textureFlags, GraphicsResourceUsage usage) in c:\DEV\paradox\sources\engine\SiliconStudio.Paradox.Graphics\Texture.cs:line 1032
   at SiliconStudio.Paradox.Graphics.Data.GpuTextureSerializer2.Serialize(ContentSerializerContext context, SerializationStream stream, Texture& texture) in c:\DEV\paradox\sources\engine\SiliconStudio.Paradox.Graphics\DataOld\GpuTextureSerializer2.cs:line 39
```

**Comment by Borkason** [comment]
Ahh, okay :)
Thanks for letting me know.
