### ISSUE TITLE
Using Paradox projects on network share

### ISSUE THREAD

**Issue by ArtiomCiumac** [SiliconStudio/paradox#186]
It's a quite long description, but I think all tested scenarios are related. Let me know if it would be better to split this issue into several different ones.

Environment: Active Directory domain and an user account with full privileges on all involved computers and network shares.
Host: Windows Server 2012, Visual Studio 2013 Update 4, Paradox 1.0.0-beta10

Issue 1, steps to reproduce:
 1. Create a network share and map it as a drive in host OS.
 2. Try to create a project located in the network-mapped drive trough Paradox Studio.
 3. The following error is displayed by Paradox Studio, however the project seems to be created correctly:

```
[]: Error: Error while loading assembly reference [Z:\Temp\HelloWorld2\HelloWorld2\Bin\Windows-Direct3D11\Debug\HelloWorld2.Game.shadow1]. System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at SiliconStudio.Core.Reflection.AssemblyContainer.LoadAssemblyFromPathInternal(String assemblyFullPath)
[]: Error: Unable to load assembly reference [Z:\Temp\HelloWorld2\HelloWorld2\Bin\Windows-Direct3D11\Debug\HelloWorld2.Game.dll]
```

Issue 2, steps to reproduce:
 1. Open the solution created from the above steps in Visual Studio.
 2. Run Clean, then Rebuild commands.
 3. The build for the game library is successful, however the build for the windows executable fails, full build output is the following:

```
1>------ Rebuild All started: Project: HelloWorld2.Game, Configuration: Debug Any CPU ------
1>  HelloWorld2.Game -> Z:\Temp\HelloWorld2\HelloWorld2\Bin\Windows-Direct3D11\Debug\HelloWorld2.Game.dll
1>  SiliconStudio AssemblyProcessor: "C:\Users\artiom\AppData\Local\Programs\Paradox\GamePackages\Paradox.1.0.0-beta10\Bin\Windows-Direct3D11\SiliconStudio.AssemblyProcessor.exe" --platform=Windows --targetFramework=v4.5  --auto-notify-property --parameter-key --auto-module-initializer --serialization "Z:\Temp\HelloWorld2\HelloWorld2\Bin\Windows-Direct3D11\Debug\HelloWorld2.Game.dll"
1>  Patch for assembly [HelloWorld2.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
2>------ Rebuild All started: Project: HelloWorld2.Windows, Configuration: Debug Any CPU ------
[BuildEngine] E: Error while loading assembly reference [Z:\Temp\HelloWorld2\HelloWorld2\Bin\Windows-Direct3D11\Debug\HelloWorld2.Game.shadow1]
[BuildEngine] E: Unable to load assembly reference [Z:\Temp\HelloWorld2\HelloWorld2\Bin\Windows-Direct3D11\Debug\HelloWorld2.Game.dll]
[BuildEngine] I: Loading Assets from Package [HelloWorld2.pdxpkg]
[BuildEngine] I: Loading Assets from Package [Paradox.pdxpkg]
2>  HelloWorld2.Windows -> Z:\Temp\HelloWorld2\HelloWorld2\Bin\Windows-Direct3D11\Debug\HelloWorld2.exe
2>  SiliconStudio AssemblyProcessor: "C:\Users\artiom\AppData\Local\Programs\Paradox\GamePackages\Paradox.1.0.0-beta10\Bin\Windows-Direct3D11\SiliconStudio.AssemblyProcessor.exe" --platform=Windows --targetFramework=v4.5  --auto-notify-property --parameter-key --auto-module-initializer --serialization "Z:\Temp\HelloWorld2\HelloWorld2\Bin\Windows-Direct3D11\Debug\HelloWorld2.exe"
2>  Patch for assembly [HelloWorld2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
2>  BuildEngine: info 0.012s: BuildEngine arguments: --platform=Windows --graphics-platform=Direct3D11 --profile=Windows --project-configuration=Debug --output-path=Z:\Temp\HelloWorld2\HelloWorld2\Bin\Windows-Direct3D11\Debug\data --build-path=Z:\Temp\HelloWorld2\HelloWorld2\HelloWorld2.Windows\..\obj\data --package-file=Z:\Temp\HelloWorld2\HelloWorld2\HelloWorld2.Windows\..\HelloWorld2.pdxpkg --log-pipe=net.pipe://localhost/Paradox.BuildEngine.Monitor.1ba710cf-2b90-4419-b841-f32e107e892f
2>  BuildEngine: info 0.012s: BuildEngine arguments: --platform=Windows --graphics-platform=Direct3D11 --profile=Windows --project-configuration=Debug --output-path=Z:\Temp\HelloWorld2\HelloWorld2\Bin\Windows-Direct3D11\Debug\data --build-path=Z:\Temp\HelloWorld2\HelloWorld2\HelloWorld2.Windows\..\obj\data --package-file=Z:\Temp\HelloWorld2\HelloWorld2\HelloWorld2.Windows\..\HelloWorld2.pdxpkg --log-pipe=net.pipe://localhost/Paradox.BuildEngine.Monitor.1ba710cf-2b90-4419-b841-f32e107e892f
2>  BuildEngine: info 0.012s: Starting builder.
2>  BuildEngine: info 0.012s: Starting builder.
2>EXEC : error 0.544s: Error while loading assembly reference [Z:\Temp\HelloWorld2\HelloWorld2\Bin\Windows-Direct3D11\Debug\HelloWorld2.Game.shadow1]
2>EXEC : error 0.544s: Error while loading assembly reference [Z:\Temp\HelloWorld2\HelloWorld2\Bin\Windows-Direct3D11\Debug\HelloWorld2.Game.shadow1]
2>  System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
2>     at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
2>     at System.Reflection.Assembly.LoadFile(String path)
2>     at SiliconStudio.Core.Reflection.AssemblyContainer.LoadAssemblyFromPathInternal(String assemblyFullPath)
2>  System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
2>     at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
2>     at System.Reflection.Assembly.LoadFile(String path)
2>     at SiliconStudio.Core.Reflection.AssemblyContainer.LoadAssemblyFromPathInternal(String assemblyFullPath)
2>EXEC : error 0.661s: Unable to load assembly reference [Z:\Temp\HelloWorld2\HelloWorld2\Bin\Windows-Direct3D11\Debug\HelloWorld2.Game.dll]
2>EXEC : error 0.661s: Unable to load assembly reference [Z:\Temp\HelloWorld2\HelloWorld2\Bin\Windows-Direct3D11\Debug\HelloWorld2.Game.dll]
2>  : info 0.661s: Loading Assets from Package [HelloWorld2.pdxpkg]
2>  : info 0.661s: Loading Assets from Package [HelloWorld2.pdxpkg]
2>  : info 0.661s: Loading Assets from Package [Paradox.pdxpkg]
2>  : info 0.661s: Loading Assets from Package [Paradox.pdxpkg]
2>C:\Users\artiom\AppData\Local\Programs\Paradox\GamePackages\Paradox.1.0.0-beta10\Targets\Paradox.targets(166,5): error MSB3073: The command ""C:\Users\artiom\AppData\Local\Programs\Paradox\GamePackages\Paradox.1.0.0-beta10\Bin\Windows-Direct3D11\SiliconStudio.Assets.CompilerApp.exe"  --platform=Windows --graphics-platform=Direct3D11 --profile=Windows --project-configuration=Debug --output-path="Z:\Temp\HelloWorld2\HelloWorld2\Bin\Windows-Direct3D11\Debug\data" --build-path="Z:\Temp\HelloWorld2\HelloWorld2\HelloWorld2.Windows\..\obj\data" --package-file="Z:\Temp\HelloWorld2\HelloWorld2\HelloWorld2.Windows\..\HelloWorld2.pdxpkg" --log-pipe="net.pipe://localhost/Paradox.BuildEngine.Monitor.1ba710cf-2b90-4419-b841-f32e107e892f"" exited with code 1.
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========
```

Issue 3, steps to reproduce:
 1. Open Paradox Studio and open new project creation window.
 2. Specify a network share as location, for example `\\server\share\projects`
 3. When the location textbox loses focus, the first backslash is removed from the location and it is transformed to `\server\share\projects`.
 4. If you still create the project - it gets created in the folder `c:\server\share\projects` and will not build with errors similar to ones from the issue 2.

Copying a pre-created project to a network share will not help as it cannot be build due to issue 2.

Such setup proves to be extremely useful for remote debugging on various computers on the same network without requiring to install the toolchain on all of them.

**Comment by xoofx** [comment]
Hi Artiom! We don't support network shares (and unlikely to support them easily), but couldn't you just mount the network location on a drive instead with thinks like `net use x: \\server\share\projects`?

**Comment by ArtiomCiumac** [comment]
I guess if it will be fixed for network drives - it should work also for UNC shares. Is there a reason why such paths are not supported? With UNC shares support it would not require any additional setup on remote computers except installing the remote debugger.
