### ISSUE TITLE
Simple Audio Example crash

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/paradox#206]
Hi,
testing version 1.1b and have crash on start for Simple Audio example.

[Game]: Error: Unexpected exception. SharpDX.SharpDXException: HRESULT: [0x80070
057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The
 parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.MediaFoundation.AudioStreamVolume.SetAllVolumes(Int32 dwCount, Sin
gle[] fVolumesRef)
   at SiliconStudio.Paradox.Audio.AudioEngine.UpdateMusicVolume()
   at SiliconStudio.Paradox.Audio.AudioEngine.ProcessMusicReady()
   at SiliconStudio.Paradox.Audio.AudioEngine.ProccessQueuedMediaSessionEvents()

   at SiliconStudio.Paradox.Audio.AudioEngine.UpdateMusicImpl()
   at SiliconStudio.Paradox.Audio.AudioEngine.Update()
   at SiliconStudio.Paradox.Audio.AudioSystem.Update(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameSystemCollection.Update(GameTime gameTime)

   at SiliconStudio.Paradox.Games.GameBase.Update(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameBase.UpdateAndProfile(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameBase.Tick()
SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_
INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.MediaFoundation.AudioStreamVolume.SetAllVolumes(Int32 dwCount, Sin
gle[] fVolumesRef)
   at SiliconStudio.Paradox.Audio.AudioEngine.UpdateMusicVolume()
   at SiliconStudio.Paradox.Audio.AudioEngine.ProcessMusicReady()
   at SiliconStudio.Paradox.Audio.AudioEngine.ProccessQueuedMediaSessionEvents()

   at SiliconStudio.Paradox.Audio.AudioEngine.UpdateMusicImpl()
   at SiliconStudio.Paradox.Audio.AudioEngine.Update()
   at SiliconStudio.Paradox.Audio.AudioSystem.Update(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameSystemCollection.Update(GameTime gameTime)

   at SiliconStudio.Paradox.Games.GameBase.Update(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameBase.UpdateAndProfile(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameBase.Tick()

Unhandled Exception: SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [G
eneral], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is in
correct.

   at SharpDX.Result.CheckError()
   at SharpDX.MediaFoundation.AudioStreamVolume.SetAllVolumes(Int32 dwCount, Sin
gle[] fVolumesRef)
   at SiliconStudio.Paradox.Audio.AudioEngine.UpdateMusicVolume()
   at SiliconStudio.Paradox.Audio.AudioEngine.ProcessMusicReady()
   at SiliconStudio.Paradox.Audio.AudioEngine.ProccessQueuedMediaSessionEvents()

   at SiliconStudio.Paradox.Audio.AudioEngine.UpdateMusicImpl()
   at SiliconStudio.Paradox.Audio.AudioEngine.Update()
   at SiliconStudio.Paradox.Audio.AudioSystem.Update(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameSystemCollection.Update(GameTime gameTime)

   at SiliconStudio.Paradox.Games.GameBase.Update(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameBase.UpdateAndProfile(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameBase.Tick()
   at SiliconStudio.Paradox.Games.GamePlatform.Tick()
   at SiliconStudio.Paradox.Games.GamePlatform.OnRunCallback()
   at SiliconStudio.Paradox.Games.GameWindowDesktop.<>c__DisplayClass2.<Run>b__0
()
   at SiliconStudio.Paradox.Games.WindowsMessageLoop.Run(Control form, RenderCal
lback renderCallback, Boolean useApplicationDoEvents)
   at SiliconStudio.Paradox.Games.GameWindowDesktop.Run()
   at SiliconStudio.Paradox.Games.GamePlatform.Run(GameContext gameContext)
   at SiliconStudio.Paradox.Games.GameBase.Run(GameContext gameContext)
   at SimpleAudio.SimpleAudioApp.Main(String[] args) in d:\!Prog\Paradox\SimpleA
udio\SimpleAudio\SimpleAudio.Windows\SimpleAudioApp.cs:line 12

**Comment by xenux** [comment]
Hi, thanks for the report.
It was working fine for you with version 1.0? Nothing about the Audio changed in version 1.1, so it is strange. Could you tell me your configuration? Are you on Windows 10?

**Comment by EmptyKeys** [comment]
got time to test 1.0 and it was the same exception. So just to be sure I installed latest drivers and it's working fine now.

**Comment by WyPeR** [comment]
Hi
testing 1.0,1.1 and 1.2 have crash on start for Simple Audio example by same error.

I tested on Windows 7 and Windows 10...

**Comment by EmptyKeys** [comment]
Bad/Old sound card drivers
