### ISSUE TITLE
Serializer problems (1.1.2)

### ISSUE THREAD

**Issue by Zulusas** [SiliconStudio/paradox#226]
On ``` var img = Asset.Load<Image>("dirt"); ``` i get this:

Could not find a serializer for the type [Texture, Image]
```
   at SiliconStudio.Core.Serialization.Assets.AssetSerializer.GetSerializer(Type storageType, Type objectType)
   at SiliconStudio.Core.Serialization.Assets.AssetManager.DeserializeObject(Queue`1 serializeOperations, AssetReference parentAssetReference, String url, Type objType, Object obj, AssetManagerLoaderSettings settings)
   at SiliconStudio.Core.Serialization.Assets.AssetManager.DeserializeObject(String url, Type type, Object obj, AssetManagerLoaderSettings settings)
   at SiliconStudio.Core.Serialization.Assets.AssetManager.Load(Type type, String url, AssetManagerLoaderSettings settings)
   at SiliconStudio.Core.Serialization.Assets.AssetManager.Load[T](String url, AssetManagerLoaderSettings settings)
   at Eldorado.GameScript.Start() in d:\C#_PROJECTS\PARADOX_PROJECTS\Eldorado_Projects\Eldorado_1_1\Eldorado\Eldorado\Eldorado.Game\GameScript.cs:line 20
   at SiliconStudio.Paradox.Engine.Processors.ScriptSystem.Update(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameSystemCollection.Update(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameBase.Update(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameBase.InitializeBeforeRun()
```

**Comment by jwollen** [comment]
This issue has been fixed on our development branch and will be integrated in the next release.
