### ISSUE TITLE
Exception on new project in Paradox Studio 1.1.3b

### ISSUE THREAD

**Issue by Zulusas** [SiliconStudio/paradox#236]
```
Paradox Version: 1.1.3-beta
GameStudio Version: 4
User: Raimis
Current Directory: D:\C#_PROJECTS\PARADOX
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Command Line Args: 
Exception type: InvalidOperationException
Exception message: Error while loading default package from [D:/C#_PROJECTS/PARADOX/GamePackages/Paradox.1.1.3-beta\Paradox.pdxpkg]: []: Error: Error while pre-loading package [D:\C#_PROJECTS\PARADOX\GamePackages\Paradox.1.1.3-beta\Paradox.pdxpkg]. System.IO.FileNotFoundException: Could not load file or assembly 'SiliconStudio.Paradox.Importer.Assimp.dll' or one of its dependencies. The specified module could not be found.
File name: 'SiliconStudio.Paradox.Importer.Assimp.dll'
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
   at SharpYaml.Serialization.AttributeRegistry.GetAttributes(MemberInfo memberInfo, Boolean inherit)
   at SiliconStudio.Core.Yaml.YamlSerializer.AtributeRegistryFilter.GetAttributes(MemberInfo memberInfo, Boolean inherit)
   at SharpYaml.Serialization.AssemblyRegistry.RegisterAssembly(Assembly assembly, IAttributeRegistry attributeRegistry)
   at SiliconStudio.Core.Yaml.YamlSerializer.CreateSerializer(Boolean keepOnlySealedOverrides, Serializer& localSerializer)
   at SiliconStudio.Core.Yaml.YamlSerializer.GetYamlSerializer(Boolean keepOnlySealedOverrides)
   at SiliconStudio.Core.Yaml.YamlSerializer.Deserialize(Stream stream)
   at SiliconStudio.Assets.Serializers.AssetYamlSerializer.Load(Stream stream, String assetFileExtension)
   at SiliconStudio.Assets.AssetSerializer.Load(Stream stream, String assetFileExtension)
   at SiliconStudio.Assets.AssetSerializer.Load(String filePath)
   at SiliconStudio.Assets.AssetSerializer.Load[T](String filePath)
   at SiliconStudio.Assets.Package.Load(ILogger log, String filePath, PackageLoadParameters loadParametersArg)



StackTrace:    at SiliconStudio.Assets.PackageStore..ctor(String installationPath, String defaultPackageName, String defaultPackageVersion)
   at SiliconStudio.Assets.PackageStore.<.cctor>b__4()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at SiliconStudio.Assets.PackageStore.get_Instance()
   at SiliconStudio.Assets.Templates.TemplateManager.FindTemplates()
   at SiliconStudio.Assets.Editor.ViewModel.Templates.TemplateCollectionViewModel..ctor(IViewModelServiceProvider serviceProvider, SessionContext sessionContext, TemplateScope scope, Boolean createSolution)
   at SiliconStudio.Assets.Editor.View.TemplatesWindow..ctor(SessionContext sessionContext, TemplateScope type, Boolean createSolution)
   at SiliconStudio.Assets.Editor.View.Services.EditorDialogService.CreateTemplateDialog(PackageSession session, TemplateScope type, Boolean createSolution)
   at SiliconStudio.Assets.Editor.ViewModel.SessionViewModel.<CreateNewSession>d__b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SiliconStudio.Assets.Editor.ViewModel.EditorViewModel.<NewSession>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SiliconStudio.Assets.Editor.ViewModel.EditorViewModel.<<.ctor>b__0>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunInternal(Window window)
   at SiliconStudio.Paradox.GameStudio.Program.Main(String[] args)
```

**Comment by xen2** [comment]
Hi,

I suspect this might be similar to #212 (Paradox doesn't support x86 for the editor). Are you by any chance on a non 64-bit Windows and/or CPU?

Thanks for the report!

**Comment by Zulusas** [comment]
I have no problems with 1.1.3b until i update Visual Studio Integration from launcher.
```
------------------
System Information
------------------
Time of this report: 7/1/2015, 14:40:11
       Machine name: PC
   Operating System: Windows 7 Enterprise 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_gdr.150316-1654)
           Language: Lithuanian (Regional Setting: Lithuanian)
System Manufacturer: Dell Inc.         
       System Model: Dell System XPS 15Z
               BIOS: Default System BIOS
          Processor: Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz (4 CPUs), ~2.8GHz
             Memory: 8192MB RAM
Available OS Memory: 8084MB RAM
          Page File: 5604MB used, 10561MB available
        Windows Dir: C:\Windows
    DirectX Version: DirectX 11
DX Setup Parameters: Not found
   User DPI Setting: 120 DPI (125 percent)
 System DPI Setting: 96 DPI (100 percent)
    DWM DPI Scaling: Disabled
     DxDiag Version: 6.01.7601.17514 64bit Unicode

```
Graphics Card: GeForceGT 525M and Intel(R) HD Graphics Family

**Comment by Zulusas** [comment]
When compile my project in visual studio 2012, i get this errors:
```
Error	1	Error while pre-loading package [D:\C#_PROJECTS\PARADOX_PROJECTS\Eldorado_Projects\Eldorado_1_1_3\Eldorado\Eldorado\Eldorado.pdxpkg]	D:\C#_PROJECTS\PARADOX_PROJECTS\Eldorado_Projects\Eldorado_1_1_3\Eldorado\Eldorado\Eldorado.Windows\EXEC	Eldorado.Windows
Error	2	Error while pre-loading package [D:\C#_PROJECTS\PARADOX_PROJECTS\Eldorado_Projects\Eldorado_1_1_3\Eldorado\Eldorado\Eldorado.pdxpkg]	D:\C#_PROJECTS\PARADOX_PROJECTS\Eldorado_Projects\Eldorado_1_1_3\Eldorado\Eldorado\Eldorado.Windows\EXEC	Eldorado.Windows
Error	3	The command ""D:\C#_PROJECTS\PARADOX\GamePackages\Paradox.1.1.3-beta\Bin\Windows-Direct3D11\SiliconStudio.Assets.CompilerApp.exe"  --platform=Windows --graphics-platform=Direct3D11 --profile=Windows --project-configuration=Debug --output-path="D:\C#_PROJECTS\PARADOX_PROJECTS\Eldorado_Projects\Eldorado_1_1_3\Eldorado\Eldorado\Bin\Windows-Direct3D11\Debug\data" --build-path="D:\C#_PROJECTS\PARADOX_PROJECTS\Eldorado_Projects\Eldorado_1_1_3\Eldorado\Eldorado\Eldorado.Windows\..\obj\data" --package-file="D:\C#_PROJECTS\PARADOX_PROJECTS\Eldorado_Projects\Eldorado_1_1_3\Eldorado\Eldorado\Eldorado.Windows\..\Eldorado.pdxpkg" --log-pipe=""" exited with code 1.	Eldorado.Windows
```

**Comment by Zulusas** [comment]
Full reinstall of pardox3d solved this issue! Thanks for patience!
