### ISSUE TITLE
Bug when I import an asset

### ISSUE THREAD

**Issue by therev123** [SiliconStudio/paradox#243]
Paradox Version: 1.1.4-beta
GameStudio Version: 4
Error Message: Unexpected exception
User: Utilisateur
Current Directory: C:\Silicon Studio Corp\Paradox
OS Version: Microsoft Windows NT 6.2.9200.0
Command Line Args: 
Exception type: IndexOutOfRangeException
Exception message: Index was outside the bounds of the array.
StackTrace:    at SiliconStudio.Paradox.Rendering.ModelViewHierarchyUpdater.Initialize(Model model)
   at SiliconStudio.Paradox.Rendering.ModelViewHierarchyUpdater..ctor(Model model)
   at SiliconStudio.Paradox.Engine.ModelComponent.ModelUpdated()
   at SiliconStudio.Paradox.Engine.ModelComponent.get_ModelViewHierarchy()
   at SiliconStudio.Paradox.Engine.Processors.ModelProcessor.Draw(RenderContext context)
   at SiliconStudio.Paradox.Engine.EntityManager.Draw(RenderContext context)
   at SiliconStudio.Paradox.Engine.SceneInstance.Draw(RenderContext context)
   at SiliconStudio.Paradox.Engine.Processors.ChildSceneProcessor.Draw(RenderContext context)
   at SiliconStudio.Paradox.Engine.EntityManager.Draw(RenderContext context)
   at SiliconStudio.Paradox.Engine.SceneInstance.Draw(RenderContext context)
   at SiliconStudio.Paradox.Engine.SceneSystem.Draw(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameSystemCollection.Draw(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameBase.Draw(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameBase.DrawFrame()
   at SiliconStudio.Paradox.Games.GameBase.Tick()
   at SiliconStudio.Paradox.Games.GamePlatform.Tick()
   at SiliconStudio.Paradox.Games.GamePlatform.OnRunCallback()
   at SiliconStudio.Paradox.Games.WindowsMessageLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at SiliconStudio.Paradox.Games.GameWindowDesktop.Run()
   at SiliconStudio.Paradox.Games.GameBase.Run(GameContext gameContext)
   at SiliconStudio.Paradox.GameStudio.ParadoxViewService.ParadoxUIThread(Object projectSession)
   at SiliconStudio.Core.Diagnostics.SafeAction.<>c__DisplayClass4.<Wrap>b__3(Object obj)

Also,I have find an other bug, when i create a folder in the paradox editor, the folder is not create in project repertory. Thanks for your attention. Sory for my bad english :3

**Comment by therev123** [comment]
I have try to import an basic model that i have create with the last release(version) of blender.

**Comment by Benlitz** [comment]
Hello Therev123,

About the folder, it is the expected behavior. We do not display empty folders so it is possible for you to mix asset files with other files if you want. Also, several source control systems do not support empty folders (git, perforce…). At some point we might allow to create or include empty folders in your asset hierarchy, a bit like Visual Studio does (it has a special section in .csproj for explicitly created empty folders), but it does not seem to be quite a priority for us.

About the issue with your model, it seems to be a bug on our side. Do you think you could provide us your model so we can reproduce it? We can give you a way to send it privately if you wish.

Thanks for the report!

**Comment by therev123** [comment]
Ok this is my model, it a very simple model, b ut i don't how I could send you my model. thanks

**Comment by Benlitz** [comment]
Hi,

Sorry for the late answer. 

If you have a Google account (gmail) you can upload it on Google Drive : https://drive.google.com/drive/
You can also use Dropbox or any solution that allows to upload small files.

Thanks!

**Comment by therev123** [comment]
My gmail address is: bryantremblay123@gmail.com

**Comment by therev123** [comment]
When the source code of paradox studio will be add to the repository?

**Comment by Benlitz** [comment]
Then if you're logged on gmail you can open the link I gave you above (https://drive.google.com/drive/) and should be able to upload your file.
By the way, what is type of your model file? Is it a .fbx, an .obj, or a .blend?

**Comment by therev123** [comment]
it's an .fbx model file
