### ISSUE TITLE
Nullref on adding empty AsyncTask

### ISSUE THREAD

**Issue by boriscallens** [SiliconStudio/paradox#269]
When attaching a new (empty) asynctask to an object a nulllref exception is thrown in SiliconStudio.Core.MicroThreading.Scheduler.Run.

Steps to reproduce:

   * Create new project
   * Create new AsyncScript with nothing in it
   * Attach script to any entity
   * Run

Current version 1.2.1-beta
Empty AsyncTask code:

	public class EmptyAsyncTask: AsyncScript
	{
		public override Task Execute()
		{
			return null;
		}
	}

Stack trace:

	[Scheduler]: Error: Unexpected exception while executing a micro-thread. Reason:
	 System.NullReferenceException: Object reference not set to an instance of an ob
	ject.
	   at SiliconStudio.Core.MicroThreading.MicroThread.<>c__DisplayClass4.<<Start>b
	__2>d__6.MoveNext()
	[Game]: Error: Unexpected exception. System.NullReferenceException: Object refer
	ence not set to an instance of an object.
	   at SiliconStudio.Core.MicroThreading.MicroThread.<>c__DisplayClass4.<<Start>b
	__2>d__6.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at SiliconStudio.Core.MicroThreading.Scheduler.Run()
	   at SiliconStudio.Paradox.Engine.Processors.ScriptSystem.Update(GameTime gameT
	ime)
	   at SiliconStudio.Paradox.Games.GameSystemCollection.Update(GameTime gameTime)

	   at SiliconStudio.Paradox.Games.GameBase.Update(GameTime gameTime)
	   at SiliconStudio.Paradox.Games.GameBase.InitializeBeforeRun()
	System.NullReferenceException: Object reference not set to an instance of an obj
	ect.
	   at SiliconStudio.Core.MicroThreading.MicroThread.<>c__DisplayClass4.<<Start>b
	__2>d__6.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at SiliconStudio.Core.MicroThreading.Scheduler.Run()
	   at SiliconStudio.Paradox.Engine.Processors.ScriptSystem.Update(GameTime gameT
	ime)
	   at SiliconStudio.Paradox.Games.GameSystemCollection.Update(GameTime gameTime)

	   at SiliconStudio.Paradox.Games.GameBase.Update(GameTime gameTime)
	   at SiliconStudio.Paradox.Games.GameBase.InitializeBeforeRun()

	Unhandled Exception: System.NullReferenceException: Object reference not set to
	an instance of an object.
	   at SiliconStudio.Core.MicroThreading.MicroThread.<>c__DisplayClass4.<<Start>b
	__2>d__6.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at SiliconStudio.Core.MicroThreading.Scheduler.Run()
	   at SiliconStudio.Paradox.Engine.Processors.ScriptSystem.Update(GameTime gameT
	ime)
	   at SiliconStudio.Paradox.Games.GameSystemCollection.Update(GameTime gameTime)

	   at SiliconStudio.Paradox.Games.GameBase.Update(GameTime gameTime)
	   at SiliconStudio.Paradox.Games.GameBase.InitializeBeforeRun()
	   at SiliconStudio.Paradox.Games.GamePlatform.OnInitCallback()
	   at SiliconStudio.Paradox.Games.GameWindowDesktop.Run()
	   at SiliconStudio.Paradox.Games.GamePlatform.Run(GameContext gameContext)
	   at SiliconStudio.Paradox.Games.GameBase.Run(GameContext gameContext)
	   at EmptyAsyncTask.EmptyAsyncTaskApp.Main(String[] args) in e:\Tests\EmptyAsyn
	cTask\EmptyAsyncTask\EmptyAsyncTask.Windows\EmptyAsyncTaskApp.cs:line 11

**Comment by xen2** [comment]
You should either:

- return Task.FromResult(true) (or Task.CompletedTask in .NET 4.6).
- put the keyword async (public override **async** Task Execute())

Otherwise, scripting will try to await a null Task.

If you really don't have any continuation and it's just a one-time action, you could also use StartupScript and override Start().

**Comment by xen2** [comment]
Note: Checked if.NET allow that (i.e. await a null Task). Seems it doesn't either, so we will keep this NullReferenceException to be coherent.

**Comment by boriscallens** [comment]
I assumed as this was the default implementation R# proposed it was a valid result.
The reason I even brought this up was that I expect many people starting out with scripting will try to do just this scenario and encounter this.
If the exception could be a little more descriptive it would make it easier to [fall in the pit of success](http://blog.codinghorror.com/falling-into-the-pit-of-success/)

**Comment by xen2** [comment]
I agree people might make same mistake.

However, I think it can be mitigated by adding Visual Studio "Script" templates that properly include the keyword "async".

Unfortunately I think we can't even control the exception because it happens inside the C# async state machine generated code.
