### ISSUE TITLE
program crash when selecting world coordinates, while a perspective camera is selected

### ISSUE THREAD

**Issue by 0bliter8or** [SiliconStudio/paradox#270]
I'm not sure if this was fixed in version 1.2.1, but 1.2.1 dose not seem to start on my computer (i.e., clicking start 1.2.1-beta just causes my computer to think for a bit and then do nothing)

running 1.1.4 crashes whenever I follow a particular set of steps from a tutorial and then try to set the transformation perspective of the camera to world coordinates. these steps are:
- import a model
- add an ambient light
- add a directional light
- add a perspective camera
- select world coordinates, while the camera is selected
- editor crashes with the following crash report saved to the copy buffer

Paradox Version: 1.1.4-beta
GameStudio Version: 4
Error Message: Unexpected exception
User: krogers
Current Directory: C:\Program Files\Silicon Studio\Paradox
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Command Line Args: 
Exception type: ArgumentException
Exception message: The only supported gizmo space for scaling is the Object space.
StackTrace:    at SiliconStudio.Paradox.Assets.Presentation.SceneEditor.Gizmos.GizmoScript.set_Space(TransformationSpace value)
   at SiliconStudio.Paradox.Assets.Presentation.SceneEditor.SceneController.<>c__DisplayClass10.<set_TransformationSpace>b__f()
   at SiliconStudio.Paradox.Assets.Presentation.SceneEditor.SceneService.<>c__DisplayClasse.<PostAction>b__c()
   at SiliconStudio.Core.MicroThreading.MicroThread.<>c__DisplayClass4.<<Start>b__2>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at SiliconStudio.Core.MicroThreading.Scheduler.Run()
   at SiliconStudio.Paradox.Engine.Processors.ScriptSystem.Update(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameSystemCollection.Update(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameBase.UpdateAndProfile(GameTime gameTime)
   at SiliconStudio.Paradox.Games.GameBase.Tick()
   at SiliconStudio.Paradox.Games.GamePlatform.Tick()
   at SiliconStudio.Paradox.Games.GamePlatform.OnRunCallback()
   at SiliconStudio.Paradox.Games.WindowsMessageLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at SiliconStudio.Paradox.Games.GameWindowDesktop.Run()
   at SiliconStudio.Paradox.Games.GameBase.Run(GameContext gameContext)
   at SiliconStudio.Paradox.Assets.Presentation.SceneEditor.SceneService.SceneParadoxThread(Object initializationSignal)
   at SiliconStudio.Core.Diagnostics.SafeAction.<>c__DisplayClass4.<Wrap>b__3(Object obj)

**Comment by boriscallens** [comment]
Regarding the silent shut down: this was what I experienced in #252 .
Did you try upgrading your launcher to v 1.3.0 (it should say 'Launcher v1.3.0' in the top bottom corner)

**Comment by xenux** [comment]
Hello 0bliter8or,

Thanks for the report. 
The crash mentioned when changing the space of the gizmo has been fixed in last version. 
What about the silent shut down? Can I close the issue?
