### ISSUE TITLE
Exception with 1.2.2b

### ISSUE THREAD

**Issue by Zulusas** [SiliconStudio/paradox#274]
Hi, when i run my project with new version (1.2.2), i got exception:
 
![error](https://cloud.githubusercontent.com/assets/10830201/9245466/ea3c7b88-41ac-11e5-80b4-93151058731e.png)

Stack trace:

```
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.Serializers.ListAllSerializer`2.Serialize(TList& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngineDesign_ScriptCollectionSerializer.Serialize(ScriptCollection& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(Object& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngine_ScriptComponentSerializer.Serialize(ScriptComponent& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(Object& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializerObject`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.Serializers.DictionaryAllSerializer`3.Serialize(TDictionary& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngine_EntitySerializer.Serialize(Entity& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.SerializeExtended(T& obj, ArchiveMode mode, SerializationStream stream, DataSerializer`1 dataSerializer)
   at SiliconStudio.Core.Serialization.SerializerExtensions.SerializeExtended[T](SerializationStream stream, T& obj, ArchiveMode mode, DataSerializer`1 dataSerializer)
   at SiliconStudio.Paradox.Engine.EntityComponent.Serializer.Serialize(EntityComponent& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngine_CameraComponentSerializer.Serialize(CameraComponent& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxRenderingComposers_SceneCameraSlotSerializer.Serialize(SceneCameraSlot& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.Serializers.ListSerializer`1.Serialize(List`1& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxRenderingComposers_SceneCameraSlotCollectionSerializer.Serialize(SceneCameraSlotCollection& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxRenderingComposers_SceneGraphicsCompositorLayersSerializer.Serialize(SceneGraphicsCompositorLayers& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(Object& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngine_SceneComponentSerializer.Serialize(SceneComponent& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(Object& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializerObject`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.Serializers.DictionaryAllSerializer`3.Serialize(TDictionary& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngine_EntitySerializer.Serialize(Entity& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngine_SceneSerializer.Serialize(Scene& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.SerializeExtended(T& obj, ArchiveMode mode, SerializationStream stream, DataSerializer`1 dataSerializer)
   at SiliconStudio.Core.Serialization.SerializerExtensions.SerializeExtended[T](SerializationStream stream, T& obj, ArchiveMode mode, DataSerializer`1 dataSerializer)
   at SiliconStudio.Core.Serialization.Contents.DataContentSerializerHelper`1.Serialize(ContentSerializerContext context, SerializationStream stream, T obj)
   at SiliconStudio.Core.Serialization.Contents.DataContentSerializer`1.Serialize(ContentSerializerContext context, SerializationStream stream, T obj)
   at SiliconStudio.Core.Serialization.Contents.DataContentSerializerWithReuse`1.Serialize(ContentSerializerContext context, SerializationStream stream, T obj)
   at SiliconStudio.Core.Serialization.Contents.ContentSerializerBase`1.Serialize(ContentSerializerContext context, SerializationStream stream, Object obj)
   at SiliconStudio.Core.Serialization.Contents.ContentSerializerContext.SerializeContent(SerializationStream stream, IContentSerializer serializer, Object objToSerialize)
   at SiliconStudio.Core.Serialization.Assets.AssetManager.DeserializeObject(Queue`1 serializeOperations, AssetReference parentAssetReference, String url, Type objType, Object obj, AssetManagerLoaderSettings settings)
   at SiliconStudio.Core.Serialization.Assets.AssetManager.DeserializeObject(String url, Type type, Object obj, AssetManagerLoaderSettings settings)
   at SiliconStudio.Core.Serialization.Assets.AssetManager.Load(Type type, String url, AssetManagerLoaderSettings settings)
   at SiliconStudio.Core.Serialization.Assets.AssetManager.Load[T](String url, AssetManagerLoaderSettings settings)
   at SiliconStudio.Paradox.Engine.SceneSystem.LoadContent()
   at SiliconStudio.Paradox.Games.GameSystemBase.SiliconStudio.Paradox.Games.IContentable.LoadContent()
   at SiliconStudio.Paradox.Games.GameSystemCollection.LoadContent()
   at SiliconStudio.Paradox.Games.GameBase.LoadContentInternal()
   at SiliconStudio.Paradox.Engine.Game.LoadContentInternal()
   at SiliconStudio.Paradox.Games.GameBase.InitializeBeforeRun()
   at SiliconStudio.Paradox.Games.GamePlatform.OnInitCallback()
   at SiliconStudio.Paradox.Games.GameWindowDesktop.Run()
   at SiliconStudio.Paradox.Games.GamePlatform.Run(GameContext gameContext)
   at SiliconStudio.Paradox.Games.GameBase.Run(GameContext gameContext)
   at Eldorado.EldoradoApp.Main(String[] args) in d:\C#_PROJECTS\PARADOX_PROJECTS\Eldorado_Projects\Eldorado_1_2\Eldorado\Eldorado\Eldorado.Windows\EldoradoApp.cs:line 12
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by xoofx** [comment]
Could you delete the folders `Bin\Windows\Debug\data` and `obj\data`  and recompile your project just to make sure?

**Comment by Zulusas** [comment]
It solves for Debug, but not for Release configuration. I created new "SpaceEscape" sample. When compile in Paradox studio, sample runs perfect (in Debug mode), but when i switch project configuration to Release (in visual studio 2012), i got same exception. It seams that i need to recompile project in Paradox studio. But paradox studio compiles only in debug mode. It is possible to switch Paradox studio to release mode?
