### ISSUE TITLE
XamlParseException after launching studio

### ISSUE THREAD

**Issue by zotax** [SiliconStudio/paradox#277]
Launcher Version: 1.3.0
Current Directory: C:\Program Files\Silicon Studio Corp\Paradox
Command Line Args: 
OS Version: Microsoft Windows NT 6.2.9200.0 (x64)
Processor Count: 8
Video configuration:
GPU 1
BitsPerPel: 32
Caption: AMD Radeon R9 200 Series
Description: AMD Radeon R9 200 Series
DeviceName: AMD Radeon R9 200 Series
DisplayFlags: 0
DisplayFrequency: 60
DitherType: 
DriverVersion: 
ICMIntent: 
ICMMethod: 
LogPixels: 96
PelsHeight: 768
PelsWidth: 1024
SettingID: AMD Radeon R9 200 Series
SpecificationVersion: 1025
Exception: XamlParseException: The invocation of the constructor on type 'TheArtOfDev.HtmlRenderer.WPF.HtmlPanel' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SiliconStudio.Eula.EulaHelper.EnsureEulaParadox12()
   at SiliconStudio.LauncherApp.Launcher.RunSafe()

InnerException:
  TypeInitializationException: The type initializer for 'TheArtOfDev.HtmlRenderer.WPF.Adapters.WpfAdapter' threw an exception.
     at TheArtOfDev.HtmlRenderer.WPF.Adapters.WpfAdapter.get_Instance()
     at TheArtOfDev.HtmlRenderer.WPF.HtmlContainer..ctor()
     at TheArtOfDev.HtmlRenderer.WPF.HtmlControl..ctor()
     at TheArtOfDev.HtmlRenderer.WPF.HtmlPanel..ctor()
     at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
     at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)

  InnerException:
    KeyNotFoundException: The given key was not present in the dictionary.
       at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
       at TheArtOfDev.HtmlRenderer.WPF.Adapters.FontFamilyAdapter.get_Name()
       at TheArtOfDev.HtmlRenderer.Core.Handlers.FontsHandler.AddFontFamily(RFontFamily fontFamily)
       at TheArtOfDev.HtmlRenderer.WPF.Adapters.WpfAdapter..ctor()
       at TheArtOfDev.HtmlRenderer.WPF.Adapters.WpfAdapter..cctor()

**Comment by Benlitz** [comment]
Hi @zotax 

This issue should be fixed right now, unfortunately you might need to reinstall Paradox, please re-download it from [this page](http://paradox3d.net/download/ ).

Could you please tell us what is your region and locale? This bug seems to occurs only on some specific locale.

**Comment by zotax** [comment]
My operating system's current locale/region setting is Hungarian/Hungary (hu-HU).
Thank you for the solution.
