### ISSUE TITLE
SoundMusic.Play is crashing at surround speaker setting

### ISSUE THREAD

**Issue by WyPeR** [SiliconStudio/paradox#288]
SoundMusic.Play is crashing at surround speaker setting in Windows OS.

Of course,

It is normal at stereo setting.

**Comment by xenux** [comment]
Thanks for the report,

Sorry I am not sure to understand the problem. Could you detail a little bit more and if possible give a repro for the crash?

**Comment by WyPeR** [comment]
a report for the crash .

![visio-surround_issue](https://cloud.githubusercontent.com/assets/4279032/9554650/5b4a9fa6-4e02-11e5-9648-5918f1bc13d0.png)

[Game]: Error: Unexpected exception. SharpDX.SharpDXException: HRESULT: [0x80070
057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The
parameter is incorrect.

at SharpDX.Result.CheckError()
at SharpDX.MediaFoundation.AudioStreamVolume.SetAllVolumes(Int32 dwCount, Sin
gle[] fVolumesRef)
at SiliconStudio.Paradox.Audio.AudioEngine.UpdateMusicVolume()
at SiliconStudio.Paradox.Audio.AudioEngine.ProcessMusicReady()
at SiliconStudio.Paradox.Audio.AudioEngine.ProccessQueuedMediaSessionEvents()

at SiliconStudio.Paradox.Audio.AudioEngine.UpdateMusicImpl()
at SiliconStudio.Paradox.Audio.AudioEngine.Update()
at SiliconStudio.Paradox.Audio.AudioSystem.Update(GameTime gameTime)
at SiliconStudio.Paradox.Games.GameSystemCollection.Update(GameTime gameTime)

at SiliconStudio.Paradox.Games.GameBase.Update(GameTime gameTime)
at SiliconStudio.Paradox.Games.GameBase.UpdateAndProfile(GameTime gameTime)
at SiliconStudio.Paradox.Games.GameBase.Tick()
SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_
INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

at SharpDX.Result.CheckError()
at SharpDX.MediaFoundation.AudioStreamVolume.SetAllVolumes(Int32 dwCount, Sin
gle[] fVolumesRef)
at SiliconStudio.Paradox.Audio.AudioEngine.UpdateMusicVolume()
at SiliconStudio.Paradox.Audio.AudioEngine.ProcessMusicReady()
at SiliconStudio.Paradox.Audio.AudioEngine.ProccessQueuedMediaSessionEvents()

at SiliconStudio.Paradox.Audio.AudioEngine.UpdateMusicImpl()
at SiliconStudio.Paradox.Audio.AudioEngine.Update()
at SiliconStudio.Paradox.Audio.AudioSystem.Update(GameTime gameTime)
at SiliconStudio.Paradox.Games.GameSystemCollection.Update(GameTime gameTime)

at SiliconStudio.Paradox.Games.GameBase.Update(GameTime gameTime)
at SiliconStudio.Paradox.Games.GameBase.UpdateAndProfile(GameTime gameTime)
at SiliconStudio.Paradox.Games.GameBase.Tick()

Unhandled Exception: SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [G
eneral], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is in
correct.

at SharpDX.Result.CheckError()
at SharpDX.MediaFoundation.AudioStreamVolume.SetAllVolumes(Int32 dwCount, Sin
gle[] fVolumesRef)
at SiliconStudio.Paradox.Audio.AudioEngine.UpdateMusicVolume()
at SiliconStudio.Paradox.Audio.AudioEngine.ProcessMusicReady()
at SiliconStudio.Paradox.Audio.AudioEngine.ProccessQueuedMediaSessionEvents()

at SiliconStudio.Paradox.Audio.AudioEngine.UpdateMusicImpl()
at SiliconStudio.Paradox.Audio.AudioEngine.Update()
at SiliconStudio.Paradox.Audio.AudioSystem.Update(GameTime gameTime)
at SiliconStudio.Paradox.Games.GameSystemCollection.Update(GameTime gameTime)

at SiliconStudio.Paradox.Games.GameBase.Update(GameTime gameTime)
at SiliconStudio.Paradox.Games.GameBase.UpdateAndProfile(GameTime gameTime)
at SiliconStudio.Paradox.Games.GameBase.Tick()
at SiliconStudio.Paradox.Games.GamePlatform.Tick()
at SiliconStudio.Paradox.Games.GamePlatform.OnRunCallback()
at SiliconStudio.Paradox.Games.GameWindowDesktop.<>c__DisplayClass2.b__0
()
at SiliconStudio.Paradox.Games.WindowsMessageLoop.Run(Control form, RenderCal
lback renderCallback, Boolean useApplicationDoEvents)
at SiliconStudio.Paradox.Games.GameWindowDesktop.Run()
at SiliconStudio.Paradox.Games.GamePlatform.Run(GameContext gameContext)
at SiliconStudio.Paradox.Games.GameBase.Run(GameContext gameContext)
at SimpleAudio.SimpleAudioApp.Main(String[] args) in d:!Prog\Paradox\SimpleA
udio\SimpleAudio\SimpleAudio.Windows\SimpleAudioApp.cs:line 12
