### ISSUE TITLE
Cannot start the editor on Windows 10

### ISSUE THREAD

**Issue by rookboom** [SiliconStudio/paradox#289]
I have uninstalled previous version of Paradox3d and installed the latest. When trying to launch the editor it crashes and asks me to save the dump. Here it is:
Paradox Version: 1.2.2-beta
GameStudio Version: 4
Current Directory: C:\Program Files\Silicon Studio\Paradox
Command Line Args: 
OS Version: Microsoft Windows NT 6.2.9200.0 (x64)
Processor Count: 4
Video configuration:
GPU 1
BitsPerPel: 32
Caption: Intel(R) HD Graphics 4600
Description: Intel(R) HD Graphics 4600
DeviceName: Intel(R) HD Graphics 4600
DisplayFlags: 0
DisplayFrequency: 60
DitherType: 
DriverVersion: 
ICMIntent: 
ICMMethod: 
LogPixels: 96
PelsHeight: 768
PelsWidth: 1024
SettingID: Intel(R) HD Graphics 4600
SpecificationVersion: 1025
Exception: InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[System.String]' to type 'System.Collections.Generic.List`1[SiliconStudio.Core.IO.UFile]'.
   at SiliconStudio.Core.Settings.SettingsValueKey`1.GetValue(Boolean searchInParentProfile, SettingsProfile profile, Boolean createInCurrentProfile)
   at SiliconStudio.Assets.Editor.ViewModel.EditorViewModel.UpdateMRU()
   at SiliconStudio.Assets.Editor.ViewModel.EditorViewModel..ctor(IViewModelServiceProvider serviceProvider, String editorName)
   at SiliconStudio.Paradox.GameStudio.GameStudioViewModel..ctor(IViewModelServiceProvider serviceProvider)
   at SiliconStudio.Paradox.GameStudio.Program.<Startup>d__d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at SiliconStudio.Paradox.GameStudio.Program.Main()

**Comment by Benlitz** [comment]
Hi,

Could you paste here the content of the file located here:
%APPDATA%\Silicon Studio Corp\Paradox\GameStudioInternal.conf

(That is C:\Users\[your_name]\AppData\Roaming\Silicon Studio Corp\Paradox)

Also, deleting this file will probably fix the problem.

**Comment by rookboom** [comment]
Great, that worked. Thanks! Here is the content of the file:

!SettingsFile
Settings:
    Internal/MostRecentlyUsedSessions: !System.Collections.Generic.List%25601[[System.String,%2520mscorlib,%2520Version=4.0.0.0,%2520Culture=neutral,%2520PublicKeyToken=b77a5c561934e089]],%2520mscorlib,%2520Version=4.0.0.0,%2520Culture=neutral,%2520PublicKeyToken=b77a5c561934e089
        - C:\Users\Johan\Documents\Paradox Projects\JumpyJet\JumpyJet.sln
    Internal/TelerikDockingLayout: <?xml version="1.0" encoding="utf-8"?><RadDocking><DocumentHost><RadSplitContainer><Items><RadPaneGroup SerializationTag="BaseDocumentGroup" TabStripPlacement="Top" SelectedIndex="0"><Items><RadDocumentPane SerializationTag="AssetView" IsDockable="True" Title="Asset view" /></Items></RadPaneGroup></Items></RadSplitContainer></DocumentHost><SplitContainers><RadSplitContainer Dock="DockedRight" Width="400" Orientation="Vertical"><Items><RadPaneGroup RelativeWidth="1" RelativeHeight="400" SelectedIndex="0"><Items><RadPane SerializationTag="PropertyGrid" IsDockable="True" Title="Property grid" /></Items></RadPaneGroup><RadPaneGroup RelativeWidth="1" RelativeHeight="200" SelectedIndex="0"><Items><RadPane SerializationTag="AssetPreview" IsDockable="True" Title="Asset preview" CanFloat="False" /><RadPane SerializationTag="ActionHistory" IsDockable="True" Title="Action history" /></Items></RadPaneGroup></Items></RadSplitContainer><RadSplitContainer Dock="DockedBottom" Height="195"><Items><RadPaneGroup SelectedIndex="0"><Items><RadPane SerializationTag="References" IsDockable="True" Title="References" /><RadPane SerializationTag="AssetLog" IsDockable="True" Title="Asset log" /><RadPane SerializationTag="BuildLog" IsDockable="True" Title="Build log" /></Items></RadPaneGroup></Items></RadSplitContainer><RadSplitContainer Dock="DockedLeft" Width="240" Orientation="Vertical"><Items><RadPaneGroup RelativeWidth="1" RelativeHeight="400" SelectedIndex="0"><Items><RadPane SerializationTag="SessionExplorer" IsDockable="True" Title="Solution explorer" /></Items></RadPaneGroup></Items></RadSplitContainer></SplitContainers></RadDocking>
    Internal/TemplatesWindowDialogLastNewSessionTemplateDirectory: C:/Users/Johan/Documents/Paradox Projects

**Comment by Benlitz** [comment]
Hi,

Your settings file looks like it was corrupted. Which version of Paradox did you uninstalled? If it's one of the first 1.0 releases, it might be because we changed a bit the settings format in the early release.

**Comment by Benlitz** [comment]
Also, I modified the code to prevent this exception to occur, this change will be integrated in the next release
