### ISSUE TITLE
ParadoxStudio crashes on Custom component that creates entities

### ISSUE THREAD

**Issue by wanderwurst** [SiliconStudio/paradox#302]
I have a custom component that instantiates copies of a reference Entity during the first Update() (because I found no other suiting spot for now).
The reference entity is part of the scene in the PStudio and the component creates several clones in a row basically like so:
```C#
public void Update(GameTime gameTime) // In component, called by my custom processor
{
    if(!clonesCreatedYet && (this.Entity != null) && (referenceEntity != null))
    {
        for(int i=0; i < 3; i++)
        {
            Entity clone = referenceEntity.Clone()
            this.Entity.AddChild(clone);
            clone.Transform.Position.X += 3;
        }
        clonesCreatedYet = true;
    }
}
```

While this code runs fine from Visual Studio (and does what it is intended to do), I can't open the project in Paradox Studio anymore. It tells me it had to close with the following exception call stack:
```
Exception: InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at SiliconStudio.Paradox.Assets.Presentation.ViewModel.SubEntityViewModel..ctor(IViewModelServiceProvider serviceProvider, SceneEditorViewModel scene, Entity assetEntity, Entity sceneEntity, EntityBase entityBase)
   at SiliconStudio.Paradox.Assets.Presentation.ViewModel.SubEntityViewModel..ctor(IViewModelServiceProvider serviceProvider, SceneEditorViewModel scene, Entity assetEntity, Entity sceneEntity, EntityBase entityBase)
   at SiliconStudio.Paradox.Assets.Presentation.ViewModel.SubEntityViewModel..ctor(IViewModelServiceProvider serviceProvider, SceneEditorViewModel scene, Entity assetEntity, Entity sceneEntity, EntityBase entityBase)
   at SiliconStudio.Paradox.Assets.Presentation.ViewModel.SceneEditorViewModel.<Initialize>d__1c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SiliconStudio.Paradox.Assets.Presentation.View.SceneEditorView.<InitializeEditor>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at SiliconStudio.Paradox.GameStudio.Program.Main()
```
When I just comment out the creation code, I can open the project again, so no problem.

However I would be glad for some clarification on these:

- Am I doing it wrong? I chose a component over a script because it has to interact on every update with all other Entities that hold another component. So I figured a component processor would only need to collect this list of other entities once per Update and then just call the custom components Updates().

- If this is the intended use, where should my creation code go? I tried to do it during the GenerateAssociatedData() call in my component processor, but that leads to an exception that the games entity collection was altered while iterating. So for now i keep it a conditional Update() thing but that feels wrong.
Also since Paradox Studio has problems with that, can I (as a workaround) just put some kind of condition in my creation code, like "if(Game.IsRunning)" to not execute when PStudio updates my component? I can not seem to find a reference to the Game though from my component context as I would from a script context?

- I also tried to split up the creation part into a script that i attached separately. This works ok, but it makes my code somewhat ugly since I have to keep track of handing references between scripts and components and also need to attach two things in PStudio whereas I would rather just stick to the component. I tried to programmatically attach the script in the GenerateAssociatedData() call, but that causes the same "Collection modified" exception. So what would be the intended approach here?

Thanks for your help

**Comment by Toasterthegamer** [comment]
this.Entity.AddChild(clone);

Not sure if you can have entities within entities like this. It would be better I think if you added the clone to the scene directly.

**Comment by xen2** [comment]
You can't add entities like this without the editor knowing.

The editor has view model and needs to be aware of all operations (how to undo them? what exactly changed? --otherwise if we had to check everything every frame it would be very slow).

However I agree that "editor-side scripts" would be useful (and we could do a full diff at the end -- it might take a few 100ms but it's not like an usual operation the user would run most of the time.

**Comment by Benlitz** [comment]
* No problem to clone an entity and add it as a child of another entity
* The problem might be that you didn't declare a proper PropertyKey for your component. You must declare it like this in your CustomComponent class, and override the GetDefaultKey() method to return it:

        public static PropertyKey<CustomComponent> Key = new PropertyKey<CustomComponent>("Key", typeof(CustomComponent));

        public override PropertyKey GetDefaultKey()
        {
            return Key;
        }

**Comment by wanderwurst** [comment]
Thanks everyone for the feedback, now it makes sense to me. Of course the editor must be able to track the changes, I hadn't thought about that.

Sorry for being a pain, but I am still very new to Paradox and I don't feel very familar with the basic concepts yet. I am having a hard time deciding what should go into a script and what into a component. But this has nothing to do with this issue, so I'll try to get some feedback in the <Answers> section. Thanks for your patience.
