### ISSUE TITLE
Adding new script crashes Paradox studio and breaks scene loading V 1.3.4

### ISSUE THREAD

**Issue by grajdeanserghei** [SiliconStudio/paradox#334]
Hi
From VS 2013 I've added a new script (BoxScript) to scene and it caused Paradox Studio crash. The error details were copied to clipboard:

Paradox Version: 1.3.4-beta
GameStudio Version: 4
Default session graphics profile: Level_10_0
Current Directory: E:\Program Files\Paradox
Command Line Args: 
OS Version: Microsoft Windows NT 6.2.9200.0 (x64)
Processor Count: 4
Video configuration:
GPU 1
BitsPerPel: 32
Caption: NVIDIA GeForce GTX 460
Description: NVIDIA GeForce GTX 460
DeviceName: NVIDIA GeForce GTX 460
DisplayFlags: 0
DisplayFrequency: 60
DitherType: 
DriverVersion: 
ICMIntent: 
ICMMethod: 
LogPixels: 96
PelsHeight: 768
PelsWidth: 1024
SettingID: NVIDIA GeForce GTX 460
SpecificationVersion: 1025
Exception: ArgumentException: No serializer available for type Material.BoxScript
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(T obj, SerializationStream stream)
   at SiliconStudio.Core.Serialization.Serializers.ListAllSerializer`2.Serialize(TList& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngineDesign_ScriptCollectionSerializer.Serialize(ScriptCollection& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(Object& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngine_ScriptComponentSerializer.Serialize(ScriptComponent& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(Object& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializerObject`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(T obj, SerializationStream stream)
   at SiliconStudio.Core.Serialization.Serializers.DictionaryAllSerializer`3.Serialize(TDictionary& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngine_EntitySerializer.Serialize(Entity& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.SerializeExtended(T& obj, ArchiveMode mode, SerializationStream stream, DataSerializer`1 dataSerializer)
   at SiliconStudio.Core.Serialization.SerializerExtensions.SerializeExtended[T](SerializationStream stream, T& obj, ArchiveMode mode, DataSerializer`1 dataSerializer)
   at SiliconStudio.Paradox.Engine.EntityComponent.Serializer.Serialize(EntityComponent& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngine_TransformComponentSerializer.Serialize(TransformComponent& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(T obj, SerializationStream stream)
   at SiliconStudio.Core.Serialization.Serializers.ListAllSerializer`2.Serialize(TList& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(Object& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngine_TransformComponentSerializer.Serialize(TransformComponent& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(Object& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializerObject`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(T obj, SerializationStream stream)
   at SiliconStudio.Core.Serialization.Serializers.DictionaryAllSerializer`3.Serialize(TDictionary& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngine_EntitySerializer.Serialize(Entity& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngineDesign_EntityDesignSerializer.Serialize(EntityDesign& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(T obj, SerializationStream stream)
   at SiliconStudio.Core.Serialization.Serializers.KeyedSortedListSerializer`3.Serialize(TKeyedList& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngineDesign_EntityHierarchyDataSerializer.Serialize(EntityHierarchyData& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxAssetsEntities_EntityAssetSerializer.Serialize(EntityAsset& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxAssetsEntities_SceneAssetSerializer.Serialize(SceneAsset& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(Object& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.SerializeExtended(T& obj, ArchiveMode mode, SerializationStream stream, DataSerializer`1 dataSerializer)
   at SiliconStudio.Core.Serialization.SerializerExtensions.SerializeExtended[T](SerializationStream stream, T obj, ArchiveMode mode, DataSerializer`1 dataSerializer)
   at SiliconStudio.Assets.AssetCloner..ctor(Object value, Boolean keepOnlySealedOverride, Boolean referencesAsNull)
   at SiliconStudio.Assets.AssetCloner.Clone(Object asset, Boolean keepOnlySealedOverride, Boolean referencesAsNull)
   at SiliconStudio.Assets.Analysis.AssetDependencyManager.Session_AssetDirtyChanged(Asset asset)
   at SiliconStudio.Assets.PackageSession.OnAssetDirtyChanged(Asset asset)
   at SiliconStudio.Assets.Package.OnAssetDirtyChanged(Asset asset)
   at SiliconStudio.Assets.AssetItem.set_IsDirty(Boolean value)
   at SiliconStudio.Assets.Editor.ViewModel.AssetViewModel.OnDirtyFlagSet(Boolean oldValue, Boolean newValue)
   at SiliconStudio.Presentation.ViewModel.DirtiableEditableViewModel.set_IsDirty(Boolean value)
   at SiliconStudio.Presentation.ViewModel.DirtiableEditableViewModel.UpdateDirtiness()
   at SiliconStudio.Presentation.ViewModel.DirtiableEditableViewModel.NotifyActionStackChange(ActionStackChange change)
   at SiliconStudio.Presentation.ViewModel.ActionStack.ViewModelTransactionalActionStack.RegisterActionItemsRecursively(IEnumerable`1 actionItems)
   at SiliconStudio.Presentation.ViewModel.ActionStack.ViewModelTransactionalActionStack.OnActionItemsAdded(ActionItemsEventArgs`1 e)
   at SiliconStudio.ActionStack.ActionStack.InternalAddRange(IActionItem[] items)
   at SiliconStudio.Presentation.ViewModel.ActionStack.ViewModelTransactionalActionStack.<>n__0(IActionItem item)
   at SiliconStudio.Presentation.ViewModel.ActionStack.ViewModelTransactionalActionStack.<>c__DisplayClass11_0.<Add>b__0()
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at SiliconStudio.Presentation.View.DispatcherService.Invoke(Action callback)
   at SiliconStudio.Presentation.ViewModel.ActionStack.ViewModelTransactionalActionStack.Add(IActionItem item)
   at SiliconStudio.Presentation.Commands.CancellableCommand.ExecuteCommand(Object parameter, Boolean createActionItem)
   at SiliconStudio.Presentation.Commands.CancellableCommand.Execute(Object parameter)
   at SiliconStudio.Presentation.Behaviors.OnEventCommandBehavior.OnEvent()
   at SiliconStudio.Presentation.Core.AnonymousEventHandler`1.Handler(Object sender, TEventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Controls.ComboBox.OnIsDropDownOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   at System.Windows.Controls.ComboBoxItem.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunInternal(Window window)
   at SiliconStudio.Paradox.GameStudio.Program.Main()

**Comment by xenux** [comment]
Hi,

Thanks for the report.
It looks like the editor is not able to serialize your script. Could you check that all the members your script class are either seriazable or marked not to serialize (DataMemberIgnore attribute on it).
Still the whole editor should not crash. Could you give us the step by step way to reproduce this crash and if possible the code of your script? 
Thanks
