### ISSUE TITLE
Can't create a new project

### ISSUE THREAD

**Issue by mattdef** [SiliconStudio/paradox#583]
Hi,

After the fisrt install, i have this error when i try to create a new project : 
```
Verbose: Loading Assets from Package [Xenko.xkpkg]
Verbose: Loading Assets from Package [FirstGame.xkpkg]
Verbose: Generating FirstGame.Game...
Verbose: Generating FirstGame.Windows...
Verbose: Loading Assets from Package [FirstGame.xkpkg]
Error: An exception occurred while generating the template.. Microsoft.Build.Exceptions.InvalidProjectFileException: The tools version "15.0" is unrecognized. Available tools versions are "14.0", "2.0", "3.5", "4.0".
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Project.Data.InitializeForEvaluation(IToolsetProvider toolsetProvider)
   at Microsoft.Build.Evaluation.Evaluator`4..ctor(IEvaluatorData`4 data, ProjectRootElement projectRootElement, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at SiliconStudio.Assets.PackageSessionHelper.SaveProperties(Package package) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\PackageSessionHelper.cs:line 344
   at SiliconStudio.Assets.Package.Save(ILogger log, PackageSaveParameters saveParameters) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\Package.cs:line 635
   at SiliconStudio.Assets.PackageSession.Save(LoggerResult log, PackageSaveParameters saveParameters) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\PackageSession.cs:line 661
   at SiliconStudio.Assets.Editor.Components.TemplateDescriptions.SessionTemplateGenerator.SaveSession(SessionTemplateGeneratorParameters parameters) in C:\TeamCity\work\80a49494ba341a6a\sources\editor\SiliconStudio.Assets.Editor\Components\TemplateDescriptions\SessionTemplateGenerator.cs:line 106
   at SiliconStudio.Xenko.Assets.Presentation.Templates.NewGameTemplateGenerator.CreateCameraScript(SessionTemplateGeneratorParameters parameters, Package package, ProjectReference projectGameReference, String projectGameName, Entity cameraEntity, AssetItem sceneAssetItem) in C:\TeamCity\work\80a49494ba341a6a\sources\editor\SiliconStudio.Xenko.Assets.Presentation\Templates\NewGameTemplateGenerator.cs:line 471
   at SiliconStudio.Xenko.Assets.Presentation.Templates.NewGameTemplateGenerator.CreateAndSetNewScene(SessionTemplateGeneratorParameters parameters, Package package, ProjectReference projectGameReference, String projectGameName) in C:\TeamCity\work\80a49494ba341a6a\sources\editor\SiliconStudio.Xenko.Assets.Presentation\Templates\NewGameTemplateGenerator.cs:line 371
   at SiliconStudio.Xenko.Assets.Presentation.Templates.NewGameTemplateGenerator.Generate(SessionTemplateGeneratorParameters parameters) in C:\TeamCity\work\80a49494ba341a6a\sources\editor\SiliconStudio.Xenko.Assets.Presentation\Templates\NewGameTemplateGenerator.cs:line 195
   at SiliconStudio.Assets.Editor.Components.TemplateDescriptions.SessionTemplateGenerator.Run(SessionTemplateGeneratorParameters parameters) in C:\TeamCity\work\80a49494ba341a6a\sources\editor\SiliconStudio.Assets.Editor\Components\TemplateDescriptions\SessionTemplateGenerator.cs:line 39
   at SiliconStudio.Assets.Editor.Components.TemplateDescriptions.TemplateGeneratorHelper.<>c__DisplayClass0_0`1.<RunTemplateGeneratorSafe>b__0() in C:\TeamCity\work\80a49494ba341a6a\sources\editor\SiliconStudio.Assets.Editor\Components\TemplateDescriptions\TemplateGeneratorHelper.cs:line 56
```

Xenko v2, Windows 10 pro and Visual Studio Community 2017

Thanks for your work

**Comment by manu-st** [comment]
Looks like a missing prerequisite.

Could you check by launching the VS 2017 installer (Win+S and type Visual Studio Installer) that you have MSBuild selected when modifying the Visual Studio Community 2017 and selecting *Individual Components*.

If it is not, then select it, install it and verify if this works or not.
If it is installed, could try to install the "Build Tools for Visual Studio 2017" at the following page https://www.visualstudio.com/downloads/ (go to the bottom, expand "Other Tools and Frameworks"?)

Let us know how it goes.

**Comment by mattdef** [comment]
Yeah ! It's works !

Thank's a lot

**Comment by manu-st** [comment]
Which solution did you choose?

**Comment by mattdef** [comment]
I have download "Build Tools for Visual Studio 2017" on visual studio website

**Comment by manu-st** [comment]
Thanks for the feedback.

**Comment by xen2** [comment]
Just to check, could it be that Xenko installed/updated VS2017 and/or MSBuild 2017, but you didn't reboot after? (a messagebox should supposedly have told you to do so)

**Comment by xen2** [comment]
Another possibility is that it asked for UAC during install to update VS2017 (message box asking you elevated permissions), but if you don't answer it in time it simply times out.
(we will soon add a loop to try again in those cases)
