### ISSUE TITLE
An error occurred while installing version 2.0.1.1. Error code -1073741819

### ISSUE THREAD

**Issue by cegjohnny** [SiliconStudio/paradox#590]
Downloaded the new installer for 2.0 a few hours ago. Launcher opens and prompts me to install a version, I agree and allow it to proceed with the installation. The launcher downloads the bits and then attempts to install prerequisites. After a few moments, a dialog opens containing the following stack trace.

Running Windows 10 (x64) with the latest updates
32GB RAM
AMD FX-8350

An error occurred while installing version 2.0.1.1. Error code -1073741819 while running install package process [C:\Users\jonat_000\AppData\Local\Programs\Silicon Studio\Xenko\GamePackages\Xenko.2.0.1.1\tools\packageinstall.exe]
Unhandled Exception: **System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.** at Microsoft.VisualStudio.Setup.Configuration.ISetupInstance2.IsComplete() at SiliconStudio.Core.VisualStudio.VisualStudioVersions.BuildIDEInfos() at SiliconStudio.Xenko.PackageInstall.Program.CheckVisualStudioAndBuildTools() at SiliconStudio.Xenko.PackageInstall.Program.Main(String[] args)
 at SiliconStudio.Packages.NugetStore.RunPackageInstall(String packageInstall, String arguments, ProgressReport progress) at SiliconStudio.Packages.NugetStore.OnPackageInstalled(Object sender, PackageOperationEventArgs args) at NuGet.PackageManager.OnInstalled(PackageOperationEventArgs e) at NuGet.PackageManager.Execute(IPackage package, IPackageOperationResolver resolver) at NuGet.PackageManager.InstallPackage(IPackage package, Boolean ignoreDependencies, Boolean allowPrereleaseVersions) at SiliconStudio.Packages.NugetStore.<InstallPackage>d71.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at SiliconStudio.LauncherApp.ViewModels.PackageVersionViewModel.<>cDisplayClass520.<<Download>b_0>d.MoveNext()

**Comment by manu-st** [comment]
It looks like the failure is related to our prerequisites trying to setup VS 2017. Do you have it installed?

Even after the stack trace during the prerequisites install, does the launcher reports a proper installation of Xenko 2.0? Were you able to launch it?

**Comment by cegjohnny** [comment]
The install halts at the display of the dialog containing the stack trace. After exiting the dialog, the launcher reverts to the pre-installation state and appears as it does upon initial launch. Sorry, I should have added that into the original post.

![image](https://cloud.githubusercontent.com/assets/28814896/26266224/7d52ca6a-3cb2-11e7-9682-d190b984e6e4.png)

**Comment by cegjohnny** [comment]
Hmmm...I have the Visual Studio Community 2017 RC. I bet that's the culprit.

**Comment by manu-st** [comment]
It could be. Could you install the final version of VS 2017 and see if it makes a difference? VS 2017 has changed quite a bit with respect to its installer and we are using a COM component that may have changed its layout in the final version. Let us know how it goes.

**Comment by cegjohnny** [comment]
Upgrading to the latest version of VS 2017 Community resolved the issue. Thank you for your assistance.
