### ISSUE TITLE
IsFixedTimeStep causes crash in 2.1.0.3

### ISSUE THREAD

**Issue by makotech222** [SiliconStudio/paradox#636]
Enabling this setting in latest version causes a null reference exception. Did not happen in 2.0

My code:
```
 class RenaissanceApp
    {
        static void Main(string[] args)
        {
            using (var game = new CustomGame())
            {
                game.Run();
            }
        }
    }

    internal class CustomGame : Game
    {
        public CustomGame()
        {
            IsFixedTimeStep = true;
            IsDrawDesynchronized = true;
            GraphicsDeviceManager.SynchronizeWithVerticalRetrace = true;
            TargetElapsedTime = TimeSpan.FromSeconds(1 / 100.0f);
        }
    }
```

Stack Trace:
```
at SiliconStudio.Xenko.Graphics.CommandList.FlushResourceBarriers()
at SiliconStudio.Xenko.Graphics.CommandList.Close()
at SiliconStudio.Xenko.Graphics.CommandList.Flush()
at SiliconStudio.Xenko.Games.GameBase.EndDraw(Boolean present)
at SiliconStudio.Xenko.Engine.Game.EndDraw(Boolean present) in C:\TeamCity\work\80a49494ba341a6a\sources\engine\SiliconStudio.Xenko.Engine\Engine\Game.cs:line 446
at SiliconStudio.Xenko.Games.GameBase.TickInternal()
at SiliconStudio.Xenko.Games.GameBase.Tick()
at SiliconStudio.Xenko.Games.GamePlatform.Tick()
at SiliconStudio.Xenko.Games.GamePlatform.OnRunCallback()
at SiliconStudio.Xenko.Games.GameWindowWinforms.<>cDisplayClass19_0.<Run>b0()
at SiliconStudio.Xenko.Games.WindowsMessageLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
at SiliconStudio.Xenko.Games.GameWindowWinforms.Run()
at SiliconStudio.Xenko.Games.GamePlatform.Run(GameContext gameContext)
at SiliconStudio.Xenko.Games.GameBase.Run(GameContext gameContext)
at Renaissance.RenaissanceApp.Main(String[] args) in C:\Users\Steven\Documents\Xenko Projects\Renaissance\Renaissance\Renaissance.Windows\RenaissanceApp.cs:line 12
```

**Comment by makotech222** [comment]
Sorry I think i was wrong. This may have to do with Texture Streaming being enabled in my project. Not sure how it was messing things up, or why disabling fixed time step worked (but then actually stopped working later).
