### ISSUE TITLE
Unable to run new project

### ISSUE THREAD

**Issue by jayrulez** [SiliconStudio/paradox#644]
```
Exception in command SiliconStudio.Xenko.Assets.Textures.TextureConvertParameters: System.TypeInitializationException: The type initializer for 'SiliconStudio.TextureConverter.TextureTool' threw an exception. ---> System.InvalidOperationException: Could not load native library DxtWrapper.dll from path [C:\Program Files\Silicon Studio\Xenko\Bin\Windows\x64\DxtWrapper.dll] using CPU architecture x64.
   at SiliconStudio.Core.NativeLibrary.PreloadLibrary(String libraryName) in C:\TeamCity\work\80a49494ba341a6a\sources\common\core\SiliconStudio.Core\Native\NativeLibrary.cs:line 70
   at SiliconStudio.TextureConverter.TextureTool..cctor() in C:\TeamCity\work\80a49494ba341a6a\sources\tools\SiliconStudio.TextureConverter\Frontend\TextureTool.cs:line 41
   --- End of inner exception stack trace ---
   at SiliconStudio.TextureConverter.TextureTool..ctor()
   at SiliconStudio.Xenko.Assets.Textures.TextureAssetCompiler.TextureConvertCommand.DoCommandOverride(ICommandContext commandContext) in C:\TeamCity\work\80a49494ba341a6a\sources\engine\SiliconStudio.Xenko.Assets\Textures\TextureAssetCompiler.cs:line 63
   at SiliconStudio.BuildEngine.CommandBuildStep.<StartCommand>d__21.MoveNext() in C:\TeamCity\work\80a49494ba341a6a\sources\common\buildengine\SiliconStudio.BuildEngine.Common\CommandBuildStep.cs:line 0
```

It seems these files are not in the expected folder. Something must be wonky with the installer.

**Comment by stefnotch** [comment]
Judging from
`C:\Program Files\Silicon Studio\Xenko\Bin\Windows\x64\DxtWrapper.dll`
and
`C:\TeamCity\work\80a49494ba341a6a\sources\common\core\SiliconStudio.Core\Native\NativeLibrary.cs`
I assume that you chose to install Xenko in some non-default location.

**Comment by xen2** [comment]
No, this is just that some assemblies have .pdb (build server paths) and some other don't (user path).

**Comment by jayrulez** [comment]
How do I get around this @xen2 ?

**Comment by xen2** [comment]
@jayrulez 
if DxtWrapper.dll doesn't load, it could be because of missing Visual C++ runtime.
To understand better, please let me know:
* Do you have Visual Studio installed?
* Did you have any issue when installing Xenko (specifically the prerequisites)?

(note: my previous answer was concerning @stefnotch remark)

**Comment by jayrulez** [comment]
I do have visual studio installed (Community 2017).

I have various versions of VS C++ runtime installed.

I didn't have any issue intalling Xenko. 

I have .NET 4.7.1 installed while Xenko requires 4.6.2 but that shouldn't be a problem.

**Comment by xen2** [comment]
Could you try to open DxtWrapper.dll with Dependency Walker x64?
http://www.dependencywalker.com/

You could then take a look at top level .dll and see if any is missing.
Here is what it look like on my computer:

![image](https://user-images.githubusercontent.com/527565/36359363-cd3d71cc-155d-11e8-9280-b6c0c8f71d1c.png)
