### ISSUE TITLE
the engine crashes

### ISSUE THREAD

**Issue by Uni44** [SiliconStudio/paradox#677]
Hi, when I try to program, the engine always crashes. I recently downloaded it and until now it was fine, but when I try to edit a script, the error comes out.

```
Application: GameStudio
UserEmail: 
UserMessage: 
XenkoVersion: 3.0.0.2
GameStudioVersion: 4
ThreadName: Main thread
DefaultGraphicProfile: Level_10_0
OpenedAssets: 4a7e615e-1ed6-44aa-8f66-20f0016fdc39:MainScene (Scene)
1e7793e8-acf2-1321-bd28-36311c01aea2:Prueba (Script Source Code)
41220870-709c-360e-c2b3-19b6cea30c30:BasicCameraController (Script Source Code)

LastActions: * +[]
        * {PropertyChangeOperation: ScriptSourceFileAssetViewModel.IsDeleted}
        * {CollectionChangeOperation: Remove}
        * {PropertyChangeOperation: ScriptSourceFileAssetViewModel.Directory}

CurrentDirectory: C:\Program Files\Xenko
CommandArgs: /LauncherWindowHandle 1116172 C:\Users\Unigames44.DESKTOP-OOO7K58.000\Documents\Xenko Projects\Prueba de Fisicas\Prueba de Fisicas.sln
OsVersion: Microsoft Windows 10 Pro 10.0.17134 x64
ProcessorCount: 4
Exception: TaskCanceledException: Se canceló una tarea.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.DocumentState.<GetSyntaxTreeAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Document.<GetSyntaxRootAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RoslynPad.Roslyn.BraceMatching.AbstractDirectiveTriviaBraceMatcher`5.<FindBracesAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RoslynPad.Roslyn.BraceMatching.BraceMatchingService.<GetMatchingBracesAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RoslynPad.Roslyn.BraceMatching.BraceMatchingServiceExtensions.<GetAllMatchingBracesAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xenko.Assets.Presentation.AssetEditors.ScriptEditor.SimpleCodeTextEditor.<CaretOnPositionChanged>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Xenko.GameStudio.Program.Main()

GPU0.AdapterCompatibility: Advanced Micro Devices, Inc.
GPU0.AdapterDACType: Internal DAC(400MHz)
GPU0.AdapterRAM: 2147483648
GPU0.Availability: 3
GPU0.Caption: AMD Radeon R7 Graphics
GPU0.ConfigManagerErrorCode: 0
GPU0.ConfigManagerUserConfig: False
GPU0.CreationClassName: Win32_VideoController
GPU0.CurrentBitsPerPixel: 32
GPU0.CurrentHorizontalResolution: 1440
GPU0.CurrentNumberOfColors: 4294967296
GPU0.CurrentNumberOfColumns: 0
GPU0.CurrentNumberOfRows: 0
GPU0.CurrentRefreshRate: 75
GPU0.CurrentScanMode: 4
GPU0.CurrentVerticalResolution: 900
GPU0.Description: AMD Radeon R7 Graphics
GPU0.DeviceID: VideoController1
GPU0.DitherType: 0
GPU0.DriverDate: 20161228000000.000000-000
GPU0.DriverVersion: 21.19.384.0
GPU0.InfFilename: oem24.inf
GPU0.InfSection: ati2mtag_CarrizoDS
GPU0.InstalledDisplayDrivers: C:\WINDOWS\System32\DriverStore\FileRepository\c0311903.inf_amd64_f6ae7df7d0b2cc15\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\c0311903.inf_amd64_f6ae7df7d0b2cc15\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\c0311903.inf_amd64_f6ae7df7d0b2cc15\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\c0311903.inf_amd64_f6ae7df7d0b2cc15\amdxc64.dll
GPU0.MaxRefreshRate: 75
GPU0.MinRefreshRate: 56
GPU0.Monochrome: False
GPU0.Name: AMD Radeon R7 Graphics
GPU0.PNPDeviceID: PCI\VEN_1002&DEV_9874&SUBSYS_87191043&REV_E2\3&11583659&0&08
GPU0.Status: OK
GPU0.SystemCreationClassName: Win32_ComputerSystem
GPU0.SystemName: DESKTOP-OOO7K58
GPU0.VideoArchitecture: 5
GPU0.VideoMemoryType: 2
GPU0.VideoModeDescription: 1440 x 900 x 4294967296 colores
GPU0.VideoProcessor: AMD Radeon Graphics Processor (0x9874)
Log: 
```

**Comment by Flavelius** [comment]
You should post this issues to the new repository: https://github.com/xenko3d/xenko
